config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root to: "users#index"

  resources  :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_comments_counter
  after_destroy :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_likes_counter
  after_destroy :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_create :update_author_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_author_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

	def current_user
		@current_user ||= User.second
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post, :set_user, only: %i[new create]
	def new
		@comment = Comment.new
		render :new
	end
	
	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id
		puts "comment_params: #{@comment_params}"
		puts "current_user: #{@current_user}"

		if @comment.save
			flash[:success] = 'Comment was successfully created.'
			redirect_to user_post_path(@user, @post)
		else
			flash.now[:error] = 'Comment could not be created.'
			render :new
		end
	end

	private

	def set_post
		@post = Post.find(params[:post_id])
	end

	def set_user
		@user = User.find(params[:user_id])
	end

	def comment_params
		@comment_params = params.require(:comment).permit(:text)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = @post.likes.build(like_params)
    @like.user_id = current_user.id

    if @like.save

      redirect_to user_post_path(@post.author_id, @post), success: "You liked this post!"
    else
      redirect_to user_post_path(@post.author_id, @post), alert: "Failed to like this post!"
    end
  end

  def destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user, only: %i[index show]

  def index
    @posts = @user.posts.paginate(page: params[:page], per_page: 2).order('created_at DESC')
  end

  def new
    @post = current_user.posts.new
    render :new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post was successfully created.'
      redirect_to user_path(current_user)
    else
      flash.now[:error] = 'Post could not be created.'
      render :new
    end
  end

  def show
    @user
    @post = @user.posts.find(params[:id])
  end

  private
  def user
    @user ||= User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Create new comment</h1>

  <% if @comment.errors.any? %>
    <div>
      <% @comment.errors.full_messages.each do |message| %>
      <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

<%= form_with model: @comment, url: user_post_comments_path do |form| %>
<%= form.label :text%>
<%= form.text_field :text, placeholder: "commment" %>
<%= form.submit "create comment" %>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VervePress</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "/layouts/flash_message"%>
    <%= yield %>
  </body>
</html>

app/views/likes/_create.html.erb
<button>
<%= link_to "like", user_post_path(@post.author_id, @post) %>
</button>

app/views/likes/_destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<div>
  <div>
    <div>
      <%= image_tag @user.photo, url: "#{@user.name}'s photo" %>
    </div>
    <div class="user">
      <h2><%= @user.name %></h2>
      <p><strong>Number of posts: </strong><%= @user.posts_counter %></p>
    </div>
  </div>
  <div>
  </div>
  <% @posts.each_with_index do |post, index| %>
    <div>
      <%= link_to user_post_path(@user, post) do %>
        <h2><%= post.title %> # <%= index + 1 %></h2>
      <% end %>
        <p><%= post.text %></p>
        <p> <span>comments:</span> <%= post.comments_counter%>, <span>likes:</span><%= post.likes_counter %> </p>
    </div>
    <div>
      <% post.recent_comments.each do |comment| %>
        <p> <%= comment.user.name %> : <%= comment.text %> </p>
      <% end %>
    </div>
  <% end %>
  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>Create new post</h1>

  <% if @post.errors.any? %>
    <div>
      <% @post.errors.full_messages.each do |message| %>
      <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

<%= form_with model: @post, url: user_posts_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "Post title" %>
  </div>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text, placeholder: "Post content" %>
  </div>
  <div>
    <%= form.submit "Create Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>
<div>
  <div>
    <div>
      <h2><%= @post.title%> </h2>
      <p>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %>  </p>
    </div>
  </div>
  <p><%= @post.text %> </p>
  <div>
    <% @post.comments.each do |comment| %>
      <p> <%= comment.user.name %> : <%= comment.text %> </p>
    <% end %>
  </div>
</div>
<button>
<%= link_to "create comment", new_user_post_comment_path(@user, @post) %>
</button>
<%= render 'likes/create' %>

app/views/users/index.html.erb
<div>
  <h1>Users#index</h1>
  <h1>Find me in app/views/users/index.html.erb</h1>
  <button>
<%= link_to "Create new Post", new_user_post_path(current_user) %>
  </button>
  <ul>
    <% @users.each do |user| %>
      <li>
			<%= link_to user_path(user) do %>
        <%= image_tag user.photo, alt: "#{user.name}'s photo" %>
        <div>
          <h1>
            <%= user.name %>
          </h1>
          <p>
            <%= pluralize(user.posts_counter, "post")%>
          </p>
        </div>
				<%end%>
      </li>
    <%end%>
  </ul>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<h1>Find me in app/views/users/show.html.erb</h1>
<div>
  <div>
    <%= image_tag @user.photo, alt: "#{@user.name}'s photo" %>
    <div>
      <h2>
        <%= @user.name %>
      </h2>
      <p>
        <%= pluralize(@user.posts_counter, "post")%>
      </p>
    </div>
  </div>
  <div>
    <h2>Bio</h2>
    <p><%= @user.bio %></p>
  </div>
  <ul>
    <% @user.recent_posts.each_with_index do |post, index| %>
      <li>
        <h3><%= link_to post.title, user_post_path(@user, post) %> <%= index + 1 %> </h3>
        <p><%= post.text %></p>
        <div>
          <span>Comments: <%= post.comments_counter %></span>
          <span>Likes: <%= post.likes_counter %></span>
        </div>
      </li>
    <% end %>
  </ul>
  <% if @user.posts_counter > 3 %>
    <button>
      <%= link_to "See all posts", user_posts_path(@user) %>
    </button>
  <% end %>
</div>